### ISSUE TITLE
Update 1.0.4 feedback

### ISSUE THREAD

**Issue by ApolloX939** [Droog71/moontest#10]
Ok so some things cool.

* Research probe (Ok with a robot it makes research a breeze, once you get to research level 4 then things really start getting good/easy and fun)
* Robot (Once I figured it out robots are very nice, can almost make one never need to leave the habitat)
* REM stuff (ok, nice image for rare metals, except for that one could make the research system but with REM miners)

> Over all, very nice stuff. (Just a few things I would have done a little different... maybe)

**Comment by Droog71** [comment]
Here is a simple program for loading rockets.
The loop at the beginning is just "loop while 2 < 1", so basically... "while true"
![rem_robot](https://user-images.githubusercontent.com/6352433/149399622-03b92471-6be4-4a60-9ff0-e2b898a182ae.png)

This program is for when the rocket and robot are setup like this:
![rocket_automation](https://user-images.githubusercontent.com/6352433/149399765-466d668d-749c-4e28-bd92-f63e2170e09c.png)

Here is one for loading research data into a crate.
The first loop is the same 'while 2 < 1'. The second loop is while the counter is < 3.
![research_robot](https://user-images.githubusercontent.com/6352433/149400181-68b0c76d-3145-4bbe-91af-7c1ec34d0b80.png)


The setup looks like this:
![research_automation](https://user-images.githubusercontent.com/6352433/149400084-d7c61d0b-0e0b-4bb9-a191-c7e556aa036b.png)

You can actually make a ton of money from the research probes like this. I had two sets of 4 last time I played through the game and I was typically getting around $8000 whenever I went and emptied the crates.

The main advantage of the REM stuff is you can set it up and forget about it for a while if you put 4 stacks of fuel in the generator, it just becomes passive income for a while.

**Comment by ApolloX939** [comment]
Ah, ok now the robots and research make more sense... a lot better than by 2 research points I have. (Just need to build it and then I should be good to go researching and making money both.

**Comment by ApolloX939** [comment]
My Research:
![screenshot_20220113_160629](https://user-images.githubusercontent.com/20930999/149409606-9a4955e2-74dd-4e16-a15c-5330224a2603.png)
(My loop is `loop, counter =, 0`, which always is true, since loops start their counter at 0, so it always is 0, this being the only change from yours)
![Screenshot_2022-01-13_16-08-14](https://user-images.githubusercontent.com/20930999/149409727-ab6bbf12-7d1a-4596-b6de-73a24d8acd58.png)

My Rare Metals: (I used a second robot because why not... once you get enough from research you can easily afford it)
![screenshot_20220113_160711](https://user-images.githubusercontent.com/20930999/149409769-4df1059a-3091-4122-867c-551b39d6d1e7.png)
(Again my loop infinite, and just configured to collect REM)
![Screenshot_2022-01-13_16-08-52](https://user-images.githubusercontent.com/20930999/149410076-8c4dcd5b-ebf3-48f2-a613-3a50ebf72429.png)
> And the loader
![Screenshot_2022-01-13_16-09-52](https://user-images.githubusercontent.com/20930999/149410104-2735deed-f2ab-42e5-9690-64eb2256c409.png)


Now the down side is I currently have 2 generators which don't fuel themselves, but I could just as easily make the loader from my REM load fuel for the generators, and thus I end why adding the robots makes things very cool. (Almost exactly like what I was thinking of)

**Comment by Droog71** [comment]
This is really cool to see. I really like the rocket loading with two robots. I have been using 4 robots with an extractor on all 4 sides of the rocket, 1 robot each.

With your method, you could easily do 16 extractors or really however many extractors you want per rocket. That means the rocket will be launching frequently and you will really be making a lot of money. Very cool!

**Comment by ApolloX939** [comment]
Yup, fun with drag and drop tech.

Not to mention I have the robot's programming on cassettes, so literally just buy the stuff needed to be placed and program the bots from the cassettes and done. (I found for bigger more complex programs it's better to buy a spare robot to keep in the habitat, rather than freezing and suffocating in space while I try to build programs)
