### ISSUE TITLE
Automation Tutorial/Examples

### ISSUE THREAD

**Issue by ApolloX939** [Droog71/moontest#8]
Just a few images I took where I tried to reduce the cost of every automation system so it's really cheap and quite effective.

> I didn't include the (minimal as possible) reactor boosters because I currently am still trying to understand how that works. (I have it working just a little more complex than all these.

### Reactor
![screenshot_20220109_164740](https://user-images.githubusercontent.com/20930999/148705083-f73edcc0-8d45-4450-8fe8-01ca213e9f7b.png)

## Oxygen Generator
![screenshot_20220109_164838](https://user-images.githubusercontent.com/20930999/148705115-edca9b8a-05fe-4c18-84c2-7226ad957d5c.png)

> And you can see how I got on top of the HVAC (simply bought a useless cheap block to climb up on, or disable the gravity gen)

## HVAC System
![screenshot_20220109_164824](https://user-images.githubusercontent.com/20930999/148705124-841ba4a0-5326-4df9-b3eb-ea78fc174491.png)

## Cooling Pump
![screenshot_20220109_164918](https://user-images.githubusercontent.com/20930999/148705144-bb03942d-74a0-450d-ab0a-6a0ec3d2bbb9.png)

## Gravity Generator
![screenshot_20220109_164947](https://user-images.githubusercontent.com/20930999/148705155-9b0efd74-e358-4c0f-acba-f62c0babd541.png)

## Drill
![screenshot_20220109_175243](https://user-images.githubusercontent.com/20930999/148705165-d4fbdbbc-15f0-4117-8686-17d67ccf8984.png)

Hope you enjoy some more material for the tutorial (perhaps put this section in a Automation section to show off the nice features of automation).

**Comment by Droog71** [comment]
This is great, thanks! I will add these to the manual or tutorial in the next update.

**Comment by ApolloX939** [comment]
Yeah I messed up on the drill, the relay is set to max delay 4 lights (but the picture shows min delay 1 light)

> Hope you can at least find a use for me. :)

**Comment by Droog71** [comment]
I added my favorite one to the manual with an explanation like this:
![manual](https://user-images.githubusercontent.com/6352433/149442701-17503d84-4986-406c-8c6b-771b5d345ff9.png)

**Comment by ApolloX939** [comment]
Yeah darn, I just realized the wire isn't really needed, the micro controller can be placed directly next to the relay, then the delayer next to it (back to the machine).

> Meh, can't always get it perfect 100% of the time.
